# Generated by Django 5.2.5 on 2025-08-30 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(max_length=200, unique=True, verbose_name="Тема"),
                ),
                (
                    "content",
                    models.TextField(max_length=200, verbose_name="Содержание"),
                ),
                (
                    "attached_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="newsletter/",
                        verbose_name="Прикрепленные файлы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["subject"],
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Created", "event created"),
                            ("Started", "event started"),
                            ("Completed", "event completed"),
                        ],
                        default="Created",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "first_sending",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время первой отправки"
                    ),
                ),
                (
                    "сompletion_time",
                    models.DateTimeField(
                        default=None,
                        null=True,
                        verbose_name="Дата и время окончания отправки",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailings.message",
                        verbose_name="Содержание рассылки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["status"],
                "permissions": [("mailing_manager", "Mailing list manager")],
            },
        ),
    ]
