# Generated by Django 5.2.5 on 2025-08-30 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mailings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="recipients",
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL, verbose_name="Получатели рассылки"
            ),
        ),
    ]
