# Generated by Django 5.2.5 on 2025-08-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="title",
            field=models.CharField(max_length=200, null=True, verbose_name="Тема"),
        ),
    ]
