# Generated by Django 5.2.5 on 2025-08-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="сompletion_time",
            field=models.DateTimeField(
                auto_created=True,
                blank=True,
                default=None,
                null=True,
                verbose_name="Дата и время окончания отправки",
            ),
        ),
    ]
