# Generated by Django 5.2.5 on 2025-08-31 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0003_alter_newsletter_сompletion_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attempt_send",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Not_start", "Did not start"),
                            ("Not_successful", "event started"),
                            ("Successful", "event completed"),
                        ],
                        default="Not_start",
                        verbose_name="Статус попытки",
                    ),
                ),
                (
                    "time_attempt",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время попытки"
                    ),
                ),
                (
                    "mail_server_response",
                    models.CharField(
                        default="Нет ответа",
                        null=True,
                        verbose_name="Ответ почтового сервера",
                    ),
                ),
                (
                    "news_letter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailings.newsletter",
                        verbose_name="Содержание рассылки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попыток рассылки",
                "ordering": ["status"],
            },
        ),
    ]
