# Generated by Django 5.2.5 on 2025-08-31 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0004_attempt_send"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Attempt_send",
            new_name="AttemptSend",
        ),
    ]
