# Generated by Django 5.2.5 on 2025-08-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0005_rename_attempt_send_attemptsend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attemptsend",
            name="status",
            field=models.CharField(
                choices=[
                    ("Start", "Start"),
                    ("Not_start", "Not start"),
                    ("Not_successful", "Warning"),
                    ("Successful", "event completed"),
                ],
                default="Not_start",
                verbose_name="Статус попытки",
            ),
        ),
    ]
